media: assets
content:
  - name: homepage
    type: collection
    path: content/homepage
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      