baseURL = 'https://przewrotka.org/'
languageCode = 'pl-PL'
title = 'PrzeWrotka'

enableRobotsTXT = true
enableEmoji = true

theme = "hugo-scroll"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables use of <sub> and other html sutff in markdown
      unsafe = true

[params]
  favicon = "images/favicon.png"
  images = ["images/przerodziny-reczniki.jpg"]
  copyright = "Made by Zuza Kawczyńska and Mati Blue ❤️"

