backend:
  name: github
  repo: WKKPrzeWrotka/przewrotka.org
  site_domain: przewrotka.org
  
media_folder: assets/images
public_folder: /images
collections:
  - name: homepage
    label: Homepage
    folder: content/homepage
    fields:
      - { name: title, label: Tytuł, widget: string }
      - { name: weight, label: Pozycja, widget: number, value_type: int}
      - { name: body, label: Treść, widget: markdown }
